// <auto-generated />
namespace Sing_Ang.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PRJ_00001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PRJ_00001));
        
        string IMigrationMetadata.Id
        {
            get { return "201601071808402_PRJ_00001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
